[package]
name = "get-example"
version = "0.1.0"
authors = ["Aleksey Kladov <aleksey.kladov@gmail.com>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2" }
ureq = { version = "1.3", default-features = false }
reqwest = { version = "0.10", default-features = false }
